services:
  lws-example:
    image: nginx-lws:${TAG:-local}
    command: [ './nginx-entrypoint.sh' ]
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: runtime
    ports:
      - "127.0.0.1:8080:80"
