FROM i386/debian:bookworm AS build32
RUN apt-get update && apt-get install -y \
    build-essential \
    bash \
	ssh git \
	nginx zlib1g-dev libpcre3-dev \
	liblua5.3-dev
SHELL ["/bin/bash", "-lc"]
WORKDIR /src