worker_processes auto;
pid /run/nginx-lws/nginx.pid;
lock_file /run/nginx-lws/nginx.lock;

load_module /opt/nginx-lws/modules/lws_module.so;

error_log /var/log/nginx-lws/error.log info;

events {
	worker_connections 768;
}

http {
	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;
	gzip on;

	access_log /var/log/nginx-lws/access.log;
	error_log /var/log/nginx-lws/error.log info;

	client_body_temp_path /run/nginx-lws/client_body;
	fastcgi_temp_path /run/nginx-lws/fastcgi;
	proxy_temp_path /run/nginx-lws/proxy;
	scgi_temp_path /run/nginx-lws/scgi;
	uwsgi_temp_path /run/nginx-lws/uwsgi;

	server {
		listen 8080;
		server_name localhost;

		location / {
			alias /workspaces/nginx-lws/examples/static/;
		}

		location ~ /services/(\w+)(/.*)? {
			lws /workspaces/nginx-lws/examples/services/$1.lua $2;
			lws_init /workspaces/nginx-lws/examples/handlers/init.lua;
			lws_pre /workspaces/nginx-lws/examples/handlers/pre.lua;
			lws_path "+/workspaces/nginx-lws/examples/modules/?.lua;/workspaces/nginx-lws/examples/modules/?/init.lua";
			lws_error_response json diagnostic;
			lws_max_requests 1;
			lws_streaming on;
		}

		location /internal/ {
			alias /workspaces/nginx-lws/examples/internal/;
			internal;
		}

		location /lws-monitor/ {
			lws_monitor;
		}
	}
}
